### ISSUE TITLE
spacy integration

### ISSUE THREAD

**Issue by tamuhey** [Hyperparticle/udify#10]
Hi, @Hyperparticle 

I integrated udify into spaCy, and [opensourced it yesterday](https://github.com/PKSHATechnology-Research/camphr).
[This is a documentation for udify](https://camphr.readthedocs.io/en/latest/notes/udify.html).

Regards,

**Comment by Hyperparticle** [comment]
Awesome work! Thanks for letting me know about this. You rock.

**Comment by Hyperparticle** [comment]
I added a link in the README.

**Comment by tamuhey** [comment]
Thank you very much!
