### ISSUE TITLE
"Training on other datasets" directions missing required flag

### ISSUE THREAD

**Issue by neubig** [Hyperparticle/udify#15]
This command in the "Training on other datasets" of the README causes the following error:

    (python3) gneubig@ogma:~/work/udify$ python train.py --config config/ud/en/udify_bert_train_en_ewt.json --name en_ewt
    Traceback (most recent call last):
      File "train.py", line 46, in <module>
        train_path = glob.glob(pathname).pop()
    IndexError: pop from empty list

Adding the `--dataset_dir` resolves the error.

    python train.py --config config/ud/en/udify_bert_train_en_ewt.json --name en_ewt --dataset_dir data/ud-treebanks-v2.3/

**Comment by Hyperparticle** [comment]
Good catch. Updated the README.
