### ISSUE TITLE
Frozen features and gold tags

### ISSUE THREAD

**Issue by niless** [Hyperparticle/udify#2]
Hi,

Is it possible to disable fine-tuning by simply changing requires_grad to false in token_embedder for a frozen feature based embedder?
Also, is there a preferred approach to just evaluate dependency parsing using gold tags for pos/feats/lemmas?

Thanks.

**Comment by Hyperparticle** [comment]
Sure, if you want to prevent your feature embedder from updating its weights, set `requires_grad` to false before passing it in.

What exactly are you evaluating? Are you saying you want to evaluate a predicted dependency tree just from the post/feats/lemma gold data alone? Seems like you'll need the gold dependency tree if you want a good evaluation, as it's globally context sensitive, while the other annotations don't need as much context.
