### ISSUE TITLE
Can I load the model using HuggingFace AutoModel ?

### ISSUE THREAD

**Issue by Hadjer13** [Hyperparticle/udify#24]
Hello, 

Is it possible to load the UDify bert-based (`udify-bert-tar-gz`) model using `AutoModel` class of HuggingFace library ? 
When downloading the model, the vocab.txt file was missing , is it the same as `bert-multilingual-base` ? 

Thanks in advance

**Comment by Hyperparticle** [comment]
The model used in UDify should be `bert-base-multilingual-cased`, as seen [here](https://github.com/Hyperparticle/udify/blob/b4c5b5e7ec8f079c005702239aca9cf916e13985/udify/models/udify_model.py#L49). This should be downloaded automatically if the code is set up properly.

**Comment by Hyperparticle** [comment]
To load with `AutoModel`, I think there might need to be a few modifications made.
