### ISSUE TITLE
Scalar mix

### ISSUE THREAD

**Issue by niless** [Hyperparticle/udify#3]
I was not able to use scalar mix option by changing `combine_layers` to `mix` from `all`. `mix_embedding` is set to 12. Is there anything else that need to change in the config file?

**Comment by Hyperparticle** [comment]
Currently, the scalar mix is computed outside the BERT embedder, one for each task. That is why all layers are returned initially. If having just one global mix instead of task specific mixes is what you want, you'll have to modify the code in the base model definition.
