### ISSUE TITLE
Multi-GPU training?

### ISSUE THREAD

**Issue by antonisa** [Hyperparticle/udify#9]
Hi, cool work!
I was wondering if the toolkit supported multi-GPU training as-is, and, if not, if there are any plans to support it.

Thanks!

**Comment by Hyperparticle** [comment]
As of last week, looks like AllenNLP now has support for distributed training on multiple GPUs. You'll have to install the package from the AllenNLP repo (see the README). I don't have much time to look into it to explain how to set it up, but you can refer [here](https://github.com/allenai/allennlp/issues/2536) for info on progress with the new multi GPU features and [here](https://github.com/allenai/allennlp/pull/3529) for the new changes.

**Comment by antonisa** [comment]
Sounds good, I'll take a look!
